name: vcf2gwas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.*
  - numpy=1.20.*
  - pandas=1.2.*
  - matplotlib=3.4.*
  - seaborn=0.11.*
  - scikit-learn=0.24.*
  - psutil=5.8.*
  - adjusttext=0.7.*
  - ipykernel
  #- jupyterlab
  - bcftools=1.12
  - plink=1.90
  - gemma=0.98.3
  - pip
  - pip:
    - umap-learn==0.5.*
